-- Migration script for creating todos and todo_checklist_items tables

-- Create the todos table
CREATE TABLE IF NOT EXISTS ops.todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    parent_id BIGINT REFERENCES ops.todos(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'in_progress', 'completed', 'archived')),
    priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high')),
    due_date TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    position INT NOT NULL DEFAULT 0
);

-- Create the todo_checklist_items table
CREATE TABLE IF NOT EXISTS ops.todo_checklist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL REFERENCES ops.todos(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    position INT NOT NULL DEFAULT 0
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_todos_status ON ops.todos(status);
CREATE INDEX IF NOT EXISTS idx_todos_priority ON ops.todos(priority);
CREATE INDEX IF NOT EXISTS idx_todos_due_date ON ops.todos(due_date);
CREATE INDEX IF NOT EXISTS idx_todos_parent_id ON ops.todos(parent_id);
CREATE INDEX IF NOT EXISTS idx_todos_user_id ON ops.todos(user_id);
CREATE INDEX IF NOT EXISTS idx_todo_checklist_items_todo_id ON ops.todo_checklist_items(todo_id);

-- Create triggers (assuming set_updated_at function already exists)
DROP TRIGGER IF EXISTS todos_updated_at ON ops.todos;
CREATE TRIGGER todos_updated_at
BEFORE UPDATE ON ops.todos
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS todo_checklist_items_updated_at ON ops.todo_checklist_items;
CREATE TRIGGER todo_checklist_items_updated_at
BEFORE UPDATE ON ops.todo_checklist_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
